image: python:3.7.3
lint:
  script:
  - pip install flake8==3.9.1
  - flake8 .
test:
  script:
  - pip install -r requirements.txt
  - pytest . --cov=wiki --cov=wiki_test --cov=format  --cov-report term-missing --cov-branch
format:
  script:
  - pip install black==21.4b2
  - black --check
type-checking:
  script:
  - pip install mypy==0.812
  - mypy .